### PR TITLE
WebGL Project Settings

### PR DESCRIPTION
**Pull request by TheMoogle**
requires issue #5 to be solved to be playable

### CODE REVIEW

**Comment by TheMoogle** [comment]
image

**Comment by ipodtouch0218** [comment]
The texture compression on the grass really hurts. Migrating sound files to ogg (or some other compressed form) instead of wav's will probably be necessary for a published WebGL build, to keep filesize relatively reasonable.

**Comment by TheMoogle** [comment]
Editor
image
DXT Compression
image
ETC2 Compression
image
ASTC Compression
image

**Comment by ipodtouch0218** [comment]
I don't think the *type* of compression on the tilesets matter, we can get away with lossless for a few, small tilesets like we have here. ASTC is obviously the best, but it still hurts a small 16x16 tile.

The biggest file size impact right now is audio, so I've went through all the audio and converted them from wav/mp3 to ogg. There isn't any discernible quality losses (sample size of 1), at about half the file size. 
I'll push the audio conversions so you can merge them into your branch.

**Comment by ipodtouch0218** [comment]
The audio changes only caused around a 1-2mb savings for the standalone builds, however it helped reduce the WebGL build down to around 13mb. Definitely reasonable for a release, I'll be putting it up on itch.

This pull request isn't necessary anymore, as the settings will already be changed in the latest commit.

**Pull request closed without merging**
