### PR TITLE
Add powerups

### PR DESCRIPTION
**Pull request by abso1utezer0**
A larger variety of powerups could add more unique experiences to matches. With the planned Super Smash Bros. inspired powerup menu coming Soon™️, it would be great to have a lot of options to choose from. This PR is a draft/work in progress.

- [ ] Hammer Suit 
  - [x] Functionality
  - [ ] Assets
    - [x] Reserve Icon
    - [x] Powerup
    - [ ] Suit
    - [x] Hammers
- [ ] Boomerang Flower
  - [ ] Functionality
  - [ ] Assets
    - [ ] Reserve Icon
    - [ ] Powerup
    - [ ] Suit
    - [ ] Boomerangs
- [ ] Tanooki Suit 
  - [ ] Functionality
  - [ ] Assets
    - [ ] Reserve Icon
    - [ ] Powerup
    - [ ] Suit
- [ ] Cat Suit 
  - [ ] Functionality (one side attack Tanooki Suit + dive)
  - [ ] Assets
    - [ ] Reserve Icon
    - [ ] Powerup
    - [ ] Suit
- [ ] Penguin Suit 
   - [ ] Functionality (just modified blue shell + ice flower)
   - [ ] Assets
     - [ ] Reserve Icon
     - [ ] Powerup
     - [ ] Suit

### CODE REVIEW

**Comment by ipodtouch0218** [comment]
quality > quantity.

also penguin suit makes no sense, it's a combination of two existing powerups.

**Comment by abso1utezer0** [comment]
> quality > quantity.
> 
> 
> 
> also penguin suit makes no sense, it's a combination of two existing powerups.

I will make sure all the power-ups are balanced and of quality. The penguin suit would be disabled by default and would have to be enabled via the planned power-up menu.

**Comment by SLG64** [comment]
What about adding a mushroom that makes you slower?

**Comment by abso1utezer0** [comment]
Closing due to horrible code and lost source code. Will restart tomorrow with a new pull and have more actually unique power-ups.

**Pull request closed without merging**
